name: hacker-news-clone-typescript                      # 1

on:
  push:
    branches:                                            # 2
      - master
      - main

jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2                        # 3
      - run: npm ci                                      # 4
      - name: Run production migration                   
        run: npm run migrate:deploy                      # 5     
        env:
          DATABASE_URL: postgres://vouedgwozmdift:9d76ec5a44f1a22bdd95d133f8b4b06c9efa7144678a376a859b78b4f3eb42d6@ec2-52-22-136-117.compute-1.amazonaws.com:5432/dc0cs8vf1u9svd
      - uses: akhileshns/heroku-deploy@v3.12.12          # 6
        with:
          heroku_api_key: 90e34b09-f742-47af-add9-1a69180d96fd
          heroku_app_name: hacker-news-clone-typescript
          heroku_email: varghese.noble230196@gmail.com